name: Builb Test and push
on: [push]
env:
  IMAGE_NAME: student_service
  REPO_NAME: gptestuser


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build docker
      run: |
        docker buildx create --name multiarch --driver docker-container --bootstrap --use
        docker buildx build --platform linux/amd64,linux/arm64 -t $REPO_NAME/$IMAGE_NAME:latest --push .