name: Builb Test and push
on: [push]
env:
  IMAGE_NAME: student_service
  REPO_NAME: gptestuser


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker
      run: |
#        docker buildx create --name multiarch --driver docker-container --bootstrap --use
#        docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 . -t $REPO_NAME/$IMAGE_NAME
         docker build build . -t $REPO_NAME/$IMAGE_NAME
    - name: run docker
      run: |
        docker run -d -e 8080:8080 -host=172.17.0.2 $REPO_NAME/$IMAGE_NAME:latest && \
          docker ps && sleep 5

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Push image to docker hub Container Registry
      run: | 
          docker push $REPO_NAME/$IMAGE_NAME